<template>
    <div class = "indexcontainer">
      <DestCard
        v-for="destination in destinations"
        :key="destination.name"
        :Destination="destination"
      />
    </div>
</template>
  
<script setup>
  import DestCard from "@/components/DestCard.vue";
  const destinations = [
    {
        name: "Amber",
        wishimg: 'https://genshin.honeyhunterworld.com/img/ambor_021_gacha_splash.webp?x28602',
        profileimg: 'https://act-webstatic.hoyoverse.com/hk4e/e20200928calculate/item_icon_u854wf/a906ddb1b9b01c9356285d40a89b6eb1.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/ambor_021_gacha_card.webp?x28602',
        type: "Pyro",
        desc: "Always energetic and full of life, Amber's the best — albeit only — Outrider of the Knights of Favonius.",
        birthday: "August 10th",
        obtainableby: "Standard Banner",
        title: "Gliding Champion",
        altname: "Outrider",
        constellation: "Lepus",
        stars: "4",
        standard: true
    },
    {
        name: "Barbara",
        wishimg: 'https://genshin.honeyhunterworld.com/img/barbara_014_gacha_splash.webp?x28602',
        profileimg: 'https://act-webstatic.hoyoverse.com/hk4e/e20200928calculate/item_icon_u854wf/59cee661e980d9e4eca196402b582f36.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/barbara_014_gacha_card.webp?x28602',
        type: "Hydro",
        desc: "Every citizen of Mondstadt adores Barbara. She learned the word 'idol' from a magazine.",
        birthday: "July 5th",
        obtainableby: "Limited and Standard Banner",
        title: "Deaconess",
        altname: "Shining Idol",
        constellation: "Crater",
        stars: "4",
        standard: true
    },
    {
        name: "Beidou",
        wishimg: 'https://genshin.honeyhunterworld.com/img/beidou_024_gacha_splash.webp?x28602',
        profileimg: 'https://act-webstatic.hoyoverse.com/hk4e/e20200928calculate/item_icon_u854wf/61d7bcde77b8a06bb7a618524af9895c.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/beidou_024_gacha_card.webp?x28602',
        type: "Electro",
        desc: "Captain of her crew, The Crux. She's quite an unbound and forthright woman.",
        birthday: "Febuary 14th",
        obtainableby: "Limited and Standard Banner",
        title: "Queen of the Crux Fleet",
        altname: "Uncrowned Lord of the Ocean",
        constellation: "Victor Mare",
        stars: "4",
        standard: true
    },
    {
        name: "Bennett",
        wishimg: 'https://genshin.honeyhunterworld.com/img/bennett_032_gacha_splash.webp?x28602',
        profileimg: 'https://act-webstatic.hoyoverse.com/hk4e/e20200928calculate/item_icon_u854wf/72cb0799091868cbe69328e90e62f94b.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/bennett_032_gacha_card.webp?x28602',
        type: "Pyro",
        desc: "An orphan discovered by an elderly adventurer as a baby, Bennett was raised in Mondstadt's Adventurers' Guild. He is the one and only member of 'Benny's Adventure Team,' as everyone else left the team after experiencing the constant misfortune that follows him.",
        birthday: "Febuary 29th",
        obtainableby: "Limited and Standard Banner",
        title: "Leader of Benny's Adventure Team",
        altname: "Trial by Fire",
        constellation: "Rota Calamitas",
        stars: "4",
        standard: true
    },
    {
        name: "Candace",
        wishimg: 'https://genshin.honeyhunterworld.com/img/candace_072_gacha_splash.webp?x28602',
        profileimg: 'https://act-webstatic.hoyoverse.com/hk4e/e20200928calculate/item_icon_u854wf/c9d510788a4db389817843334d14f18d.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/candace_072_gacha_card.webp?x28602',
        type: "Hydro",
        desc: "The scion of Al-Ahmar and the Guardian of Aaru Village, Candace is kind to travelers who visit, but is unforgiving to those who violate the village's rules.",
        birthday: "May 3rd",
        obtainableby: "Limited and Standard Banner",
        title: "Guardian of Aaru Village",
        altname: "Golden Vow",
        constellation: "Sagitta Scutum",
        stars: "4",
        standard: true
    },
    {
        name: "Charlotte",
        wishimg: 'https://genshin.honeyhunterworld.com/img/charlotte_088_gacha_splash.webp?x28602',
        profileimg: 'https://upload-static.hoyoverse.com/hoyolab-wiki/2023/11/06/35428890/7bbbff3f35661a93b5091b1f17fae6c0_6927814687713967999.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/charlotte_088_gacha_card.webp?x28602',
        type: "Cryo",
        desc: "A journalist from The Steambird, Charlotte is always on the prowl for an exclusive scoop. Ever so relentless and indefatigable, she won't stop until she finds out the truth, even if she comes closer to danger.",
        birthday: "April 10th",
        obtainableby: "Limited and Standard Banner",
        title: "Reporter of The Steambird",
        altname: "Lens of Verity",
        constellation: "Hualina Veritas",
        stars: "4",
        standard: true
    },
    {
        name: "Chevreuse",
        wishimg: 'https://genshin.honeyhunterworld.com/img/chevreuse_090_gacha_splash.webp?x28602',
        profileimg: 'https://act-webstatic.hoyoverse.com/hk4e/e20200928calculate/item_icon_u854wf/8cbaf1b000db247e384f5c8979619724.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/chevreuse_090_gacha_card.webp?x28602',
        type: "Pyro",
        desc: "She is the captain of the Maison Gardiennage's Special Security and Surveillance Patrol.",
        birthday: "January 10th",
        obtainableby: "Limited and Standard Banner",
        title: "Special Security and Surveillance Patrol Captain",
        altname: "Executor of Justice",
        constellation: "Sclopetum Ensiferum",
        stars: "4",
        standard: true
    },
    {
        name: "Chongyun",
        wishimg: 'https://genshin.honeyhunterworld.com/img/chongyun_036_gacha_splash.webp?x28602',
        profileimg: 'https://act-webstatic.hoyoverse.com/hk4e/e20200928calculate/item_icon_u854wf/db61061c68adefdeeb6b98ecf1cc681a.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/chongyun_036_gacha_card.webp?x28602',
        type: "Cryo",
        desc: "Born with an excess of yang (positive) energy, Chongyun has become a highly effective exorcist in Liyue — so effective to the point where he hasn't seen a spirit himself, as they immediately flee when he approaches.",
        birthday: "September 7th",
        obtainableby: "Limited and Standard Banner",
        title: "anisher of Evil and Rumors Thereof",
        altname: "Frozen Ardor",
        constellation: "Nubis Caesor",
        stars: "4",
        standard: true
    },
    {
        name: "Collei",
        wishimg: 'https://genshin.honeyhunterworld.com/img/collei_067_gacha_splash.webp?x28602',
        profileimg: 'https://act-webstatic.hoyoverse.com/hk4e/e20200928calculate/item_icon_u854wf/4da2bceaecdc6b95db44e00cfad2daf2.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/collei_067_gacha_card.webp?x28602',
        type: "Dendro",
        desc: " Originally an Eleazar-afflicted victim of Fatui human experimentation, Collei wandered the world as a vagrant until she met Amber in Mondstadt. Since then, Collei has turned her life around, and currently serves as a trainee Forest Ranger in the Avidya Forest.",
        birthday: "May 8th",
        obtainableby: "Limited and Standard Banner",
        title: "Avidya Forest Ranger Trainee",
        altname: "Sprout of Rebirth",
        constellation: "Leptailurus Cervarius",
        stars: "4",
        standard: true
    },
    {
        name: "Dehya",
        wishimg: 'https://genshin.honeyhunterworld.com/img/dehya_079_gacha_splash.webp?x28602',
        profileimg: 'https://act-webstatic.hoyoverse.com/hk4e/e20200928calculate/item_icon_u854wf/7d1d3025ea6ef82d8da302d5aa972c10.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/dehya_079_gacha_card.webp?x28602',
        type: "Pyro",
        desc: "A fierce and strong warrior, the 'Flame-Mane' Dehya is considered a legend among the Eremites for her might, passion, and conscientiousness. Unwilling to be trapped by the conditions that force most from the desert to stay there, she aspires to deliver hope back to the sands that she considers her home.",
        birthday: "April 7th",
        obtainableby: "Auric Blaze, Limited, and Standard Banner",
        title: "Unfettered Desert Mercenary",
        altname: "Flame-Mane",
        constellation: "Mantichora",
        stars: "5",
        standard: true
    },
    {
        name: "Diluc",
        wishimg: 'https://genshin.honeyhunterworld.com/img/diluc_016_gacha_splash.webp?x28602',
        profileimg: 'https://act-webstatic.hoyoverse.com/hk4e/e20200928calculate/item_icon_u854wf/ea056dcab267a0ba18162adeb3d27888.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/diluc_016_gacha_card.webp?x28602',
        type: "Pyro",
        desc: "Born into the affluent Ragnvindr Clan, Diluc is the current owner of the Dawn Winery and a nobleman of high esteem in Mondstadt. While a past incident caused him to split ways with the Knights of Favonius, he continues to protect Mondstadt in his own way.",
        birthday: "April 30th",
        obtainableby: "Limited and Standard Banner",
        title: "Master of the Dawn Winery",
        altname: "The Dark Side of Dawn",
        constellation: "Noctua",
        stars: "5",
        standard: true
    },
    {
        name: "Diona",
        wishimg: 'https://genshin.honeyhunterworld.com/img/diona_039_gacha_splash.webp?x28602',
        profileimg: 'https://act-webstatic.hoyoverse.com/hk4e/e20200928calculate/item_icon_u854wf/0d3685dbc5880c0e8dd73ca402201ce0.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/diona_039_gacha_card.webp?x28602',
        type: "Cryo",
        desc: "Despite being a bartender at the Cat's Tail, she loathes alcohol and will stop at nothing to ruin Mondstadt's wine industry — a feat easier said than done when her patrons absolutely love her drinks. She is the daughter of Draff, a hunter in Springvale.",
        birthday: "January 18th",
        obtainableby: "Limited and Standard Banner",
        title: "Popular bartender of the Cat's Tail",
        altname: "Kätzlein Cocktail",
        constellation: "Feles",
        stars: "4",
        standard: true
    },
    {
        name: "Dori",
        wishimg: 'https://genshin.honeyhunterworld.com/img/dori_068_gacha_splash.webp?x28602',
        profileimg: 'https://act-webstatic.hoyoverse.com/hk4e/e20200928calculate/item_icon_u854wf/d67b40071c18495cff3a46bfbf9d61f1.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/dori_068_gacha_card.webp?x28602',
        type: "Electro",
        desc: "The owner of The Palace of Alcazarzaray and a merchant of high regard, 'Lord Sangemah Bay' is well known for her ability to obtain anything a person needs, as long as they have enough Mora to afford her jaw-dropping prices.",
        birthday: "December 21st",
        obtainableby: "Limited and Standard Banner",
        title: "Sumeru Merchant",
        altname: "Treasure of Dream Garden",
        constellation: "Magicae Lucerna",
        stars: "4",
        standard: true
    },
    {
        name: "Faruzan",
        wishimg: 'https://genshin.honeyhunterworld.com/img/faruzan_076_icon_70.webp?x28602',
        profileimg: 'https://act-webstatic.hoyoverse.com/hk4e/e20200928calculate/item_icon_u854wf/10ae4ff19a542115b41e5a94678a5777.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/faruzan_076_gacha_card.webp?x28602',
        type: "Anemo",
        desc: "She is a renowned professor of the Sumeru Akademiya and member of the Haravatat Darshan. She recently returned to the Akademiya after solving a puzzle and escaping the ruins that trapped her a century ago.",
        birthday: "August 20th",
        obtainableby: "Limited and Standard Banner",
        title: "Haravatat Household Name",
        altname: "Enigmatic Machinist",
        constellation: "Flosculi Implexi",
        stars: "4",
        standard: true
    },
    {
        name: "Fischl",
        wishimg: 'https://genshin.honeyhunterworld.com/img/fischl_031_gacha_splash.webp?x28602',
        profileimg: 'https://act-webstatic.hoyoverse.com/hk4e/e20200928calculate/item_icon_u854wf/a3b70e51669b5ab3012b74129d2a5812.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/fischl_031_gacha_card.webp?x28602',
        type: "Electro",
        desc: "She is an investigator for Mondstadt's Adventurers' Guild, accompanied by the night raven Oz. A daring adventurer with seemingly outlandish theories that happen to turn out to be true, she claims to hail from a world beyond Teyvat.",
        birthday: "May 27th",
        obtainableby: "Limited and Standard Banner",
        title: "Sovereign of Immernachtreich",
        altname: "Prinzessin der Verurteilung!",
        constellation: "Corvus",
        stars: "4",
        standard: true
    },
    {
        name: "Freminet",
        wishimg: 'https://genshin.honeyhunterworld.com/img/freminet_085_gacha_splash.webp?x28602',
        profileimg: 'https://act-webstatic.hoyoverse.com/hk4e/e20200928calculate/item_icon_u854wf/ce8c1cfe3ade451fb5bddb50e9253e08.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/freminet_085_gacha_card.webp?x28602',
        type: "Cryo",
        desc: "Despite his skill and experience as a professional diver, Freminet prefers to stay out of the spotlight, content to simply carry out orders and find peace next to the Tidalga and Romaritime Flowers underwater",
        birthday: "September 24th",
        obtainableby: "Limited and Standard Banner",
        title: "Renowned Diver of the Court of Fontaine",
        altname: "Yearning for Unseen Depths",
        constellation: "Automaton",
        stars: "4",
        standard: true
    },
    {
        name: "Gaming",
        wishimg: 'https://genshin.honeyhunterworld.com/img/gaming_092_gacha_splash.webp?x28602',
        profileimg: 'https://act-upload.hoyoverse.com/event-ugc-hoyowiki/2024/01/29/35428890/b041ad23a9d6245efac952a9379c5114_8939761424130236195.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/gaming_092_gacha_card.webp?x28602',
        type: "Pyro",
        desc: "Born in Qiaoying Village, Gaming left his birthplace after an impasse with his father to pursue his passion and become a professional Wushou dancer, training constantly to make the dance popular throughout Teyvat.",
        birthday: "December 22nd",
        obtainableby: "Limited and Standard Banner",
        title: "'Sword and Strongbox' Transport Guard",
        altname: "Leonine Vanguard",
        constellation: "Leo Expergiscens",
        stars: "4",
        standard: true
    },
    {
        name: "Gorou",
        wishimg: 'https://genshin.honeyhunterworld.com/img/gorou_055_gacha_splash.webp?x28602',
        profileimg: 'https://act-webstatic.hoyoverse.com/hk4e/e20200928calculate/item_icon_u854wf/50b3930cd5e4e6fc7889f29d15fc06dd.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/gorou_055_gacha_card.webp?x28602',
        type: "Geo",
        desc: "He is a general of the Watatsumi Army. Courageous and reliable, his men know they can place their trust in him both on and off of the battlefield.",
        birthday: "May 18th",
        obtainableby: "Limited and Standard Banner",
        title: "General of the Watatsumi Army",
        altname: "Canine Warrior",
        constellation: "Canis Bellatoris",
        stars: "4",
        standard: true
    },
    {
        name: "Jean",
        wishimg: 'https://genshin.honeyhunterworld.com/img/qin_003_gacha_splash.webp?x28602',
        profileimg: 'https://act-webstatic.hoyoverse.com/hk4e/e20200928calculate/item_icon_u854wf/2a70468b694ce53008386fe9987c7e83.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/qin_003_gacha_card.webp?x28602',
        type: "Anemo",
        desc: "The older sister of Barbara, and a descendant of the prestigious Gunnhildr Clan, Jean is the Acting Grand Master of the Knights of Favonius. She is always busy handling unrest across Mondstadt and tirelessly working to maintain the City of Freedom.",
        birthday: "March 14th",
        obtainableby: "Limited and Standard Banner",
        title: "Acting Grand Master",
        altname: "Dandelion Knight",
        constellation: "Leo Minor",
        stars: "5",
        standard: true
    },
    {
        name: "Kaeya",
        wishimg: 'https://genshin.honeyhunterworld.com/img/kaeya_015_gacha_splash.webp?x28602',
        profileimg: 'https://act-webstatic.hoyoverse.com/hk4e/e20200928calculate/item_icon_u854wf/a394197b81c5722b635e7af359c0a520.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/kaeya_015_gacha_card.webp?x28602',
        type: "Cryo",
        desc: "Kaeya is the Cavalry Captain of the Knights of Favonius. He is held in high regard by the people of Mondstadt — even with all his eccentricities and secrets.",
        birthday: "November 30th",
        obtainableby: "Standard Banner",
        title: "Quartermaster of the Knights",
        altname: "Frostwind Swordsman",
        constellation: "Pavo Ocellus",
        stars: "4",
        standard: true
    },
    {
        name: "Kaveh",
        wishimg: 'https://genshin.honeyhunterworld.com/img/kaveh_081_gacha_splash.webp?x28602',
        profileimg: 'https://act-webstatic.hoyoverse.com/hk4e/e20200928calculate/item_icon_u854wf/2330b14769f843c50b869da0b22ef260.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/kaveh_081_gacha_card.webp?x28602',
        type: "Dendro",
        desc: "A renowned architect from Sumeru who perhaps cares a bit too much about too many things. He is an aesthete troubled by reality.",
        birthday: "July 9th",
        obtainableby: "Limited and Standard Banner",
        title: "Renowned Sumeru Architect",
        altname: "Empyrean Reflection",
        constellation: "Paradisaea",
        stars: "4",
        standard: true
    },
    {
        name: "Keqing",
        wishimg: 'https://genshin.honeyhunterworld.com/img/keqing_042_gacha_splash.webp?x28602',
        profileimg: 'https://act-webstatic.hoyoverse.com/hk4e/e20200928calculate/item_icon_u854wf/eb4c6449bf2467c4cad3bdeaac921e7e.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/keqing_042_gacha_card.webp?x28602',
        type: "Electro",
        desc: "As the Yuheng of the Liyue Qixing, she is someone who seeks her own answers instead of idly letting chaos run amok in Liyue. She chooses her own path with her own power and ability, instead of letting the gods determine her fate.",
        birthday: "November 20th",
        obtainableby: "Dance of Lanterns, Limited, and Standard Banner",
        title: "Yuheng of the Liyue Qixing",
        altname: "Driving Thunder",
        constellation: "Trulla Cementarii",
        stars: "5",
        standard: true
    },
    {
        name: "Kirara",
        wishimg: 'https://genshin.honeyhunterworld.com/img/momoka_061_gacha_splash.webp?x28602',
        profileimg: 'https://act-webstatic.hoyoverse.com/hk4e/e20200928calculate/item_icon_u854wf/1cb3d7d4d65741943bbfd3eccffa36b4.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/momoka_061_gacha_card.webp?x28602',
        type: "Dendro",
        desc: "A courier for Komaniya Express, a delivery company in Inazuma. A nekomata who loves her job and human society.",
        birthday: "January 22nd",
        obtainableby: "Limited and Standard Banner",
        title: "Gold Level Courier of the Komaniya Express",
        altname: "Cat Upon the Eaves",
        constellation: "Arcella",
        stars: "4",
        standard: true
    },
    {
        name: "Kujou Sara",
        wishimg: 'https://genshin.honeyhunterworld.com/img/sara_056_gacha_splash.webp?x28602',
        profileimg: 'https://act-webstatic.hoyoverse.com/hk4e/e20200928calculate/item_icon_u854wf/99e63faff7c7b6982e64d6ea861a51d5.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/sara_056_gacha_card.webp?x28602',
        type: "Electro",
        desc: "A tengu, Sara is the adopted daughter of the Kujou Clan of the Tenryou Commission. Loyal to both her clan and the Shogun, Sara carries out her orders by the Shogun's will.",
        birthday: "July 14th",
        obtainableby: "Limited and Standard Banner",
        title: "General of the Tenryou Commission",
        altname: "Crowfeather Kaburaya",
        constellation: "Flabellum",
        stars: "4",
        standard: true
    },
    {
        name: "Kuki Shinobu",
        wishimg: 'https://genshin.honeyhunterworld.com/img/shinobu_065_gacha_splash.webp?x28602',
        profileimg: 'https://act-webstatic.hoyoverse.com/hk4e/e20200928calculate/item_icon_u854wf/64e4aa06d6d8985b56aee971d7fd7724.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/shinobu_065_gacha_card.webp?x28602',
        type: "Electro",
        desc: "The capable and reliable deputy leader of the 'Arataki Gang.'' Please note: capable and reliable are not appellations for the 'Arataki Gang,'' but for their deputy leader in specific.",
        birthday: "July 27th",
        obtainableby: "Limited and Standard Banner",
        title: "Deputy Leader of the Arataki Gang",
        altname: "Mender of Tribulations",
        constellation: "Tribulatio Demptio",
        stars: "4",
        standard: true
    },
    {
        name: "Layla",
        wishimg: 'https://genshin.honeyhunterworld.com/img/layla_074_gacha_splash.webp?x28602',
        profileimg: 'https://act-webstatic.hoyoverse.com/hk4e/e20200928calculate/item_icon_u854wf/5c9faf073e9703c61acf9f6777c47b73.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/layla_074_gacha_card.webp?x28602',
        type: "Cryo",
        desc: "She is a student in the Rtawahist Darshan, specializing in Theoretical Astrology. Chronically sleep-deprived and of poor health as a result, Layla believes that 'The Stars' Blessing' is the reason she wakes from sleepwalking to find her papers fully completed.",
        birthday: "December 19th",
        obtainableby: "Limited and Standard Banner",
        title: "Half-Awake, Half-Asleep, All Incredulous",
        altname: "Fantastical Evening Star",
        constellation: "Luscinia",
        stars: "4",
        standard: true
    },
    {
        name: "Lisa",
        wishimg: 'https://genshin.honeyhunterworld.com/img/lisa_006_gacha_splash.webp?x28602',
        profileimg: 'https://act-webstatic.hoyoverse.com/hk4e/e20200928calculate/item_icon_u854wf/8e27b689ec486c954398c968ee36a626.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/lisa_006_gacha_card.webp?x28602',
        type: "Electro",
        desc: "A powerful mage recognized as Sumeru Akademiya's most distinguished graduate in 200 years, Lisa has since returned to Mondstadt to become the humble Librarian of the Knights of Favonius.",
        birthday: "June 9th",
        obtainableby: "Limited Banner",
        title: "The Librarian",
        altname: "Witch of Purple Rose",
        constellation: "Tempus Fugit",
        stars: "4",
        standard: true
    },
    {
        name: "Lynette",
        wishimg: 'https://genshin.honeyhunterworld.com/img/linette_083_gacha_splash.webp?x28602',
        profileimg: 'https://act-webstatic.hoyoverse.com/hk4e/e20200928calculate/item_icon_u854wf/7341da3f51143384b08fdeebae5365b6.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/linette_083_gacha_card.webp?x28602',
        type: "Anemo",
        desc: "Quiet and reserved, Lynette functions as a magician's assistant to her brother Lyney. After their parents' death and having been saved from an abusive noble by their 'Father', Lynette has also served as 'eyes' and 'ears' for the House of the Hearth.",
        birthday: "Febuary 2nd",
        obtainableby: "Limited and Standard Banner",
        title: "'Multi-Function Magic Assistant'",
        altname: "Elegance in the Shadows",
        constellation: "Felis Alba",
        stars: "4",
        standard: true
    },
    {
        name: "Mika",
        wishimg: 'https://genshin.honeyhunterworld.com/img/mika_080_side_icon_70.webp?x28602',
        profileimg: 'https://act-webstatic.hoyoverse.com/hk4e/e20200928calculate/item_icon_u854wf/ad4be577444a41051955f34310744c9c.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/mika_080_gacha_card.webp?x28602',
        type: "Cryo",
        desc: "A young knight born to an ordinary family. He serves as a Front-Line Surveyor in his Company. He is a low-key and cautious character.",
        birthday: "August 11h",
        obtainableby: "Limited and Standard Banner",
        title: "Front-Line Land Surveyor of the Knights of Favonius",
        altname: "Coordinates of Clear Frost",
        constellation: "Palumbus",
        stars: "4",
        standard: true
    },
    {
        name: "Mona",
        wishimg: 'https://genshin.honeyhunterworld.com/img/mona_041_gacha_splash.webp?x28602',
        profileimg: 'https://act-webstatic.hoyoverse.com/hk4e/e20200928calculate/item_icon_u854wf/c9c2f095772abe102792fc184672d5e2.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/mona_041_gacha_card.webp?x28602',
        type: "Hydro",
        desc: "A mysterious young astrologer who proclaims herself to be 'Astrologist Mona Megistus,' and who possesses abilities to match the title. Erudite, but prideful.",
        birthday: "August 31st",
        obtainableby: "Limited and Standard Banner",
        title: "Enigmatic Astrologer",
        altname: "Astral Reflection",
        constellation: "Astrolabos",
        stars: "5",
        standard: true
    },
    {
        name: "Nahida",
        wishimg: 'https://genshin.honeyhunterworld.com/img/nahida_073_gacha_splash.webp?x28602',
        profileimg: 'https://act-webstatic.hoyoverse.com/hk4e/e20200928calculate/item_icon_u854wf/99e73b84df09a2a67b2a7f86ee0a0ec4.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/nahida_073_gacha_card.webp?x28602',
        type: "Dendro",
        desc: "As Lesser Lord Kusanali, she strives to have a stronger presence in Sumeru now that she has been freed from her extensive confinement in the Sanctuary of Surasthana.",
        birthday: "October 27th",
        obtainableby: "The Moongrass' Enligtenment",
        title: "Lesser Lord Kusanali",
        altname: "Physic of Purity",
        constellation: "Sapientia Oromasdis",
        stars: "5",
        standard: false
    },
    {
        name: "Ningguang",
        wishimg: 'https://genshin.honeyhunterworld.com/img/ningguang_027_gacha_splash.webp?x28602',
        profileimg: 'https://act-webstatic.hoyoverse.com/hk4e/e20200928calculate/item_icon_u854wf/46313c80082fc8134d5d4ac963daef98.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/ningguang_027_gacha_card.webp?x28602',
        type: "Geo",
        desc: "The Tianquan of the Liyue Qixing and owner of the floating Jade Chamber in the skies of Liyue, Ningguang is a mogul who shakes the very foundations of business circles. Even grabbing a few scraps from the documents she shreds from the Jade Chamber will gift one an invaluable fragment of her wisdom, enough to stay a step or two from one's peers.",
        birthday: "August 26th",
        obtainableby: "Limited and Standard Banner",
        title: "Lady of the Jade Chamber",
        altname: "Eclipsing Star",
        constellation: "Opus Aequilibrium",
        stars: "4",
        standard: true
    },
    {
        name: "Noelle",
        wishimg: 'https://genshin.honeyhunterworld.com/img/noel_034_gacha_splash.webp?x28602',
        profileimg: 'https://act-webstatic.hoyoverse.com/hk4e/e20200928calculate/item_icon_u854wf/bb4c5deba479d43eae4ac80df322837f.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/noel_034_gacha_card.webp?x28602',
        type: "Geo",
        desc: "A maid who faithfully serves the Knights of Favonius. She dreams of joining their ranks someday.",
        birthday: "March 21st",
        obtainableby: "Limited and Standard Banner",
        title: "Maid of Favonius",
        altname: "Chivalric Blossom",
        constellation: "Parma Cordis",
        stars: "4",
        standard: true
    },
    {
        name: "Qiqi",
        wishimg: 'https://genshin.honeyhunterworld.com/img/qiqi_035_gacha_splash.webp?x28602',
        profileimg: 'https://wiki.hoyolab.com/_ipx/f_webp/https://bbs.hoyolab.com/hoyowiki/picture/character/Qiqi_icon.png',
        cardimg: 'https://genshin.honeyhunterworld.com/img/qiqi_035_gacha_card.webp?x28602',
        type: "Cryo",
        desc: "Resurrected as a zombie by the adepti, she has ended up in Baizhu's care and now works at Bubu Pharmacy in Liyue Harbor.",
        birthday: "March 3rd",
        obtainableby: "Limited and Standard Banner",
        title: "Pharmacist, Bubu Pharmacy",
        altname: "Icy Resurrection",
        constellation: "Pristina Nola",
        stars: "5",
        standard: true
    },
    {
        name: "Razor",
        wishimg: 'https://genshin.honeyhunterworld.com/img/razor_020_gacha_splash.webp?x28602',
        profileimg: 'https://act-webstatic.hoyoverse.com/hk4e/e20200928calculate/item_icon_u854wf/401fc0f666ec394c60b3ab0d4378196f.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/razor_020_gacha_card.webp?x28602',
        type: "Electro",
        desc: "Abandoned as an infant, Razor was taken in by the Wolf of the North Andrius and raised by his wolf pack in Wolvendom. After a chance encounter with Varka, the current Grand Master of the Knights of Favonius, he has slowly started integrating with humans again through the help of his teacher Lisa.",
        birthday: "September 9th",
        obtainableby: "Limited and Standard Banner",
        title: "Legend of Wolvendom",
        altname: "Wolf Boy",
        constellation: "Lupis Minor",
        stars: "4",
        standard: true
    },
    {
        name: "Rosaria",
        wishimg: 'https://genshin.honeyhunterworld.com/img/rosaria_045_gacha_splash.webp?x28602',
        profileimg: 'https://act-webstatic.hoyoverse.com/hk4e/e20200928calculate/item_icon_u854wf/4eae6d29d8063db603f379ac1cc342e4.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/rosaria_045_gacha_card.webp?x28602',
        type: "Cryo",
        desc: "The least devout among the nuns of the Church of Favonius, Rosaria prefers acting in the shadows rather than participating in the activities of the Church.",
        birthday: "January 24th",
        obtainableby: "Limited and Standard Banner",
        title: "A Nonconforming Sister",
        altname: "Thorny Benevolence",
        constellation: "Spinea Corona",
        stars: "4",
        standard: true
    },
    {
        name: "Sayu",
        wishimg: 'https://genshin.honeyhunterworld.com/img/sayu_053_gacha_splash.webp?x28602',
        profileimg: 'https://act-webstatic.hoyoverse.com/hk4e/e20200928calculate/item_icon_u854wf/81740e04f53029f8c7a1ce0a4d480369.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/sayu_053_gacha_card.webp?x28602',
        type: "Anemo",
        desc: "A ninja from the Shuumatsuban that is struggling with growing tall. Sayu believes that sleeping can help her growth, which is why she prefers to use her ninja techniques to hide and 'laze around.'",
        birthday: "October 19th",
        obtainableby: "Limited and Standard Banner",
        title: "Shuumatsuban's Resident Ninja",
        altname: "Mujina Ninja",
        constellation: "Nyctereutes Minor",
        stars: "4",
        standard: true
    },
    {
        name: "Shikanoin Heizou",
        wishimg: 'https://genshin.honeyhunterworld.com/img/heizo_059_gacha_splash.webp?x28602',
        profileimg: 'https://act-webstatic.hoyoverse.com/hk4e/e20200928calculate/item_icon_u854wf/25e949cbe4a3391246951b13aa1f0e09.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/heizo_059_gacha_card.webp?x28602',
        type: "Anemo",
        desc: "He is the number one Tenryou Commission detective, harboring a rivalry with the Bantan Sango Detective Agency's Sango.",
        birthday: "July 24th",
        obtainableby: "Limited and Standard Banner",
        title: "Detective of the Tenryou Commission",
        altname: "Analytical Harmony",
        constellation: "Cervus Minor",
        stars: "4",
        standard: true
    },
    {
        name: "Sucrose",
        wishimg: 'https://genshin.honeyhunterworld.com/img/sucrose_043_gacha_splash.webp?x28602',
        profileimg: 'https://act-webstatic.hoyoverse.com/hk4e/e20200928calculate/item_icon_u854wf/d67563812daeb7833fc0b2193ae60d51.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/sucrose_043_gacha_card.webp?x28602',
        type: "Anemo",
        desc: "An alchemist specializing in bio-alchemy, she also serves as an assistant for Albedo, the head alchemist of the Knights of Favonius.",
        birthday: "November 26th",
        obtainableby: "Limited and Standard Banner",
        title: "Knights of Favonius Alchemist",
        altname: "Harmless Sweetie",
        constellation: "Ampulla",
        stars: "4",
        standard: true
    },
    {
        name: "Thoma",
        wishimg: 'https://genshin.honeyhunterworld.com/img/tohma_050_gacha_splash.webp?x28602',
        profileimg: 'https://act-webstatic.hoyoverse.com/hk4e/e20200928calculate/item_icon_u854wf/6cf38441c1520fac55389e45c4d148e2.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/tohma_050_gacha_card.webp?x28602',
        type: "Pyro",
        desc: "Hailing from Mondstadt, Thoma is the sociable and responsible housekeeper for the Kamisato Clan and a well-known 'fixer' in Inazuma. Having amassed a powerful network of people, Thoma defends the rights and interests of the Yashiro Commission with utmost seriousness.",
        birthday: "January 9th",
        obtainableby: "Limited and Standard Banner",
        title: "The Kamisato Clan's Housekeeper",
        altname: "Protector from Afar",
        constellation: "Rubeum Scutum",
        stars: "4",
        standard: true
    },
    {
        name: "Tighnari",
        wishimg: 'https://genshin.honeyhunterworld.com/img/tighnari_069_gacha_splash.webp?x28602',
        profileimg: 'https://upload-static.hoyoverse.com/hoyolab-wiki/2022/08/22/35428890/497dd6fac3d3c652a367c67428550747_306268558608889633.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/tighnari_069_gacha_card.webp?x28602',
        type: "Dendro",
        desc: "Tighnari is the stern Chief Officer of the Forest Rangers and Collei's mentor. Despite his intelligence, he prefers to live a solitary life in the depths of Avidya Forest rather than in the ivory tower of Sumeru Akademiya.",
        birthday: "December 29th",
        obtainableby: "Limited and Standard Banner, Viridescent Vigil",
        title: "Avidya Forest Watcher",
        altname: "Verdant Strider",
        constellation: "Vulpes Zerda",
        stars: "5",
        standard: true
    },
    {
        name: "Xiangling",
        wishimg: 'https://genshin.honeyhunterworld.com/img/xiangling_023_gacha_splash.webp?x28602',
        profileimg: 'https://act-webstatic.hoyoverse.com/hk4e/e20200928calculate/item_icon_u854wf/34934a78f56e63f56a161f15087d846d.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/xiangling_023_gacha_card.webp?x28602',
        type: "Pyro",
        desc: "She is the Head Chef at the Wanmin Restaurant and runs it alongside her father Chef Mao. As a chef, Xiangling isn't afraid to try out different recipes or 'exotic' ingredients, making her dishes sometimes quite unique.",
        birthday: "November 2nd",
        obtainableby: "Limited and Standard Banner",
        title: "Chef de Cusine",
        altname: "Exquisite Delicacy",
        constellation: "Trulla",
        stars: "4",
        standard: true
    },
    {
        name: "Xingqiu",
        wishimg: 'https://genshin.honeyhunterworld.com/img/xingqiu_025_gacha_splash.webp?x28602',
        profileimg: 'https://act-webstatic.hoyoverse.com/hk4e/e20200928calculate/item_icon_u854wf/316a7d9924316f4ec326039c11452d44.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/xingqiu_025_gacha_card.webp?x28602',
        type: "Hydro",
        desc: "He is the second son of the Guild Manager of the Feiyun Commerce Guild, an influential group in Liyue, and is also a self-proclaimed practitioner of the Guhua Clan's arts. Also an avid reader, Xingqiu aims to be the embodiment of chivalry like the heroes from the books he reads; however, this belies his knack for mischief.",
        birthday: "October 9th",
        obtainableby: "Limited and Standard Banner",
        title: "Guhua Guru of Feiyun Fame",
        altname: "Juvenile Galant",
        constellation: "Fabulae Textile",
        stars: "4",
        standard: true
    },
    {
        name: "Xinyan",
        wishimg: 'https://genshin.honeyhunterworld.com/img/xinyan_044_gacha_splash.webp?x28602',
        profileimg: 'https://act-webstatic.hoyoverse.com/hk4e/e20200928calculate/item_icon_u854wf/13947038bb8df5ad8daa7c552aeb58d8.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/xinyan_044_gacha_card.webp?x28602',
        type: "Pyro",
        desc: "Rock 'n' roll is a relatively unpopular style of music in Liyue, having recently been brought over from Fontaine. Xinyan, however, loves the sound — and she's slowly but surely amassing a fanbase of her own as she performs throughout Liyue Harbor.",
        birthday: "October 16th",
        obtainableby: "Limited and Standard Banner",
        title: "Liyue's sole rock 'n' roll musician",
        altname: "Blazing Riff",
        constellation: "Fila Ignium",
        stars: "4",
        standard: true
    },
    {
        name: "Yanfei",
        wishimg: 'https://genshin.honeyhunterworld.com/img/feiyan_048_gacha_splash.webp?x28602',
        profileimg: 'https://act-webstatic.hoyoverse.com/hk4e/e20200928calculate/item_icon_u854wf/9673d854a6760e0019001c46b7f1dd65.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/feiyan_048_gacha_card.webp?x28602',
        type: "Pyro",
        desc: "One of the few half-illuminated-beasts who have not signed a contract with Rex Lapis, Yanfei nevertheless works for the betterment of Liyue as a premier legal adviser who values fairness.",
        birthday: "July 28th",
        obtainableby: "Limited and Standard Banner",
        title: "Liyue Harbor's famed legal adviser",
        altname: "Wise Innocence",
        constellation: "Bestia Iustitia",
        stars: "4",
        standard: true
    },
    {
        name: "Yaoyao",
        wishimg: 'https://genshin.honeyhunterworld.com/img/yaoyao_077_gacha_splash.webp?x28602',
        profileimg: 'https://act-webstatic.hoyoverse.com/hk4e/e20200928calculate/item_icon_u854wf/794e9009c2984a3d569d2690c2da1866.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/yaoyao_077_gacha_card.webp?x28602',
        type: "Dendro",
        desc: "Hailing from a rural area not far from Qingce Village, Yaoyao grew up with nature at her side. Seeing potential in Yaoyao, Streetward Rambler took her in as her disciple, and Yaoyao left the tranquil mountains to live with her master in the bright and bustling Liyue Harbor.",
        birthday: "March 6th",
        obtainableby: "Limited and Standard Banner",
        title: "Disciple of Streetward Rambler",
        altname: "Burgeoning Grace",
        constellation: "Osmanthus",
        stars: "4",
        standard: true
    },
    {
        name: "Yunjin",
        wishimg: 'https://genshin.honeyhunterworld.com/img/yunjin_064_gacha_splash.webp?x28602',
        profileimg: 'https://act-webstatic.hoyoverse.com/hk4e/e20200928calculate/item_icon_u854wf/98276e51ffe135707af1088c4c2f45e7.png?x-oss-process=image%2Fformat%2Cwebp',
        cardimg: 'https://genshin.honeyhunterworld.com/img/yunjin_064_gacha_card.webp?x28602x',
        type: "Geo",
        desc: "A famous figure in Liyue Harbor's opera scene, Yun Jin is the director of the Yun-Han Opera Troupe, and performs at Heyu Tea House from time to time. She is also a playwright, having written all the plays the Yun-Han Opera Troupe has performed in recent years, including a new ending for 'The Divine Damsel of Devastation.'",
        birthday: "May 21st",
        obtainableby: "Limited and Standard Banner",
        title: "Current Director of Yun-Han Opera Troupe",
        altname: "Stage Lucida",
        constellation: "Opera Grandis",
        stars: "4",
        standard: true
    },
    {
        name: "Dragon's Bane",
        wishimg: 'https://genshin.honeyhunterworld.com/img/i_n13401_gacha_icon.webp?x28602',
        profileimg: 'https://genshin.honeyhunterworld.com/img/i_n13401.webp?x28602', 
        cardimg: 'https://genshin.honeyhunterworld.com/img/i_n13401_gacha_icon.webp?x28602',
        type: "Polearm",
        desc: "",
        birthday: null,
        obtainableby: "Weapon Banner",
        title: null,
        altname: null,
        constellation: null,
        stars: "4",
        standard: true
    },
    {
        name: "Eye of Perception",
        wishimg: 'https://genshin.honeyhunterworld.com/img/i_n14409_gacha_icon.webp?x28602',
        profileimg: 'https://genshin.honeyhunterworld.com/img/i_n14409.webp?x28602',
        cardimg: 'https://genshin.honeyhunterworld.com/img/i_n14409_gacha_icon.webp?x28602',
        type: "Catalyst",
        desc: "",
        birthday: null,
        obtainableby: "Weapon Banner",
        title: null,
        altname: null,
        constellation: null,
        stars: "4",
        standard: true
    },
    {
        name: "Favonius Codex",
        wishimg: 'https://genshin.honeyhunterworld.com/img/i_n14401_gacha_icon.webp?x28602',
        profileimg: 'https://genshin.honeyhunterworld.com/img/i_n14401.webp?x28602',
        cardimg: 'https://genshin.honeyhunterworld.com/img/i_n14401_gacha_icon.webp?x28602',
        type: "Catalyst",
        desc: "",
        birthday: null,
        obtainableby: "Weapon Banner",
        title: null,
        altname: null,
        constellation: null,
        stars: "4",
        standard: true
    },
    {
        name: "Favonius Greatsword",
        wishimg: 'https://genshin.honeyhunterworld.com/img/i_n12401_gacha_icon.webp?x28602',
        profileimg: 'https://genshin.honeyhunterworld.com/img/i_n12401.webp?x28602',
        cardimg: 'https://genshin.honeyhunterworld.com/img/i_n12401_gacha_icon.webp?x28602',
        type: "Claymore",
        desc: "",
        birthday: null,
        obtainableby: "Weapon Banner",
        title: null,
        altname: null,
        constellation: null,
        stars: "4",
        standard: true
    },
    {
        name: "Favonius Lance",
        wishimg: 'https://genshin.honeyhunterworld.com/img/i_n13407_gacha_icon.webp?x28602',
        profileimg: 'https://genshin.honeyhunterworld.com/img/i_n13407.webp?x28602',
        cardimg: 'https://genshin.honeyhunterworld.com/img/i_n13407_gacha_icon.webp?x28602',
        type: "Polearm",
        desc: "",
        birthday: null,
        obtainableby: "Weapon Banner",
        title: null,
        altname: null,
        constellation: null,
        stars: "4",
        standard: true
    },
    {
        name: "Favonius Sword",
        wishimg: 'https://genshin.honeyhunterworld.com/img/i_n11401_gacha_icon.webp?x28602',
        profileimg: 'https://genshin.honeyhunterworld.com/img/i_n11401.webp?x28602',
        cardimg: 'https://genshin.honeyhunterworld.com/img/i_n11401_gacha_icon.webp?x28602',
        type: "Sword",
        desc: "",
        birthday: null,
        obtainableby: "Weapon Banner",
        title: null,
        altname: null,
        constellation: null,
        stars: "4",
        standard: true
    },
    {
        name: "Favonius Warbow",
        wishimg: 'https://genshin.honeyhunterworld.com/img/i_n15401_gacha_icon.webp?x28602',
        profileimg: 'https://genshin.honeyhunterworld.com/img/i_n15401.webp?x28602',
        cardimg: 'https://genshin.honeyhunterworld.com/img/i_n15401_gacha_icon.webp?x28602',
        type: "Bow",
        desc: "",
        birthday: null,
        obtainableby: "Weapon Banner",
        title: null,
        altname: null,
        constellation: null,
        stars: "4",
        standard: false
    },
    {
        name: "Lion's Roar",
        wishimg: 'https://genshin.honeyhunterworld.com/img/i_n11405_gacha_icon.webp?x28602',
        profileimg: 'https://genshin.honeyhunterworld.com/img/i_n11405.webp?x28602',
        cardimg: 'https://genshin.honeyhunterworld.com/img/i_n11405_gacha_icon.webp?x28602',
        type: "Sword",
        desc: "",
        birthday: null,
        obtainableby: "Weapon Banner",
        title: null,
        altname: null,
        constellation: null,
        stars: "4",
        standard: true
    },
    {
        name: "Rainslasher",
        wishimg: 'https://genshin.honeyhunterworld.com/img/i_n12405_gacha_icon.webp?x28602',
        profileimg: 'https://genshin.honeyhunterworld.com/img/i_n12405.webp?x28602',
        cardimg: 'https://genshin.honeyhunterworld.com/img/i_n12405_gacha_icon.webp?x28602',
        type: "Claymore",
        desc: "",
        birthday: null,
        obtainableby: "Weapon Banner",
        title: null,
        altname: null,
        constellation: null,
        stars: "4",
        standard: true
    },
    {
        name: "Rust",
        wishimg: 'https://genshin.honeyhunterworld.com/img/i_n15405_gacha_icon.webp?x28602',
        profileimg: 'https://genshin.honeyhunterworld.com/img/i_n15405.webp?x28602',
        cardimg: 'https://genshin.honeyhunterworld.com/img/i_n15405_gacha_icon.webp?x28602',
        type: "Bow",
        desc: "",
        birthday: null,
        obtainableby: "Weapon Banner",
        title: null,
        altname: null,
        constellation: null,
        stars: "4",
        standard: true
    },
    {
        name: "Sacrificial Bow",
        wishimg: 'https://genshin.honeyhunterworld.com/img/i_n15403_gacha_icon.webp?x28602',
        profileimg: 'https://genshin.honeyhunterworld.com/img/i_n15403.webp?x28602',
        cardimg: 'https://genshin.honeyhunterworld.com/img/i_n15403_gacha_icon.webp?x28602',
        type: "Bow",
        desc: "",
        birthday: null,
        obtainableby: "Weapon Banner",
        title: null,
        altname: null,
        constellation: null,
        stars: "4",
        standard: true
    },
    {
        name: "Sacraficial Fragments",
        wishimg: 'https://genshin.honeyhunterworld.com/img/i_n14403_gacha_icon.webp?x28602',
        profileimg: 'https://genshin.honeyhunterworld.com/img/i_n14403.webp?x28602',
        cardimg: 'https://genshin.honeyhunterworld.com/img/i_n14403_gacha_icon.webp?x28602',
        type: "Catalyst",
        desc: "",
        birthday: null,
        obtainableby: "Weapon Banner",
        title: null,
        altname: null,
        constellation: null,
        stars: "4",
        standard: true
    },
    {
        name: "Sacraficial Greatsword",
        wishimg: 'https://genshin.honeyhunterworld.com/img/i_n12403_gacha_icon.webp?x28602',
        profileimg: 'https://genshin.honeyhunterworld.com/img/i_n12403.webp?x28602',
        cardimg: 'https://genshin.honeyhunterworld.com/img/i_n12403_gacha_icon.webp?x28602',
        type: "Claymore",
        desc: "",
        birthday: null,
        obtainableby: "Weapon Banner",
        title: null,
        altname: null,
        constellation: null,
        stars: "4",
        standard: true
    },
    {
        name: "Sacraficial Sword",
        wishimg: 'https://genshin.honeyhunterworld.com/img/i_n11403_gacha_icon.webp?x28602',
        profileimg: 'https://genshin.honeyhunterworld.com/img/i_n11403.webp?x28602',
        cardimg: 'https://genshin.honeyhunterworld.com/img/i_n11403_gacha_icon.webp?x28602',
        type: "Sword",
        desc: "",
        birthday: null,
        obtainableby: "Weapon Banner",
        title: null,
        altname: null,
        constellation: null,
        stars: "4",
        standard: true
    },
    {
        name: "The Bell",
        wishimg: 'https://genshin.honeyhunterworld.com/img/i_n12402_gacha_icon.webp?x28602',
        profileimg: 'https://genshin.honeyhunterworld.com/img/i_n12402.webp?x28602',
        cardimg: 'https://genshin.honeyhunterworld.com/img/i_n12402_gacha_icon.webp?x28602',
        type: "Claymore",
        desc: "",
        birthday: null,
        obtainableby: "Weapon Banner",
        title: null,
        altname: null,
        constellation: null,
        stars: "4",
        standard: true
    },
    {
        name: "The Flute",
        wishimg: 'https://genshin.honeyhunterworld.com/img/i_n11402_gacha_icon.webp?x28602',
        profileimg: 'https://genshin.honeyhunterworld.com/img/i_n11402.webp?x28602',
        cardimg: 'https://genshin.honeyhunterworld.com/img/i_n11402_gacha_icon.webp?x28602',
        type: "Sword",
        desc: "",
        birthday: null,
        obtainableby: "Weapon Banner",
        title: null,
        altname: null,
        constellation: null,
        stars: "4",
        standard: true
    },
    {
        name: "The Stringless",
        wishimg: 'https://genshin.honeyhunterworld.com/img/i_n15402_gacha_icon.webp?x28602',
        profileimg: 'https://genshin.honeyhunterworld.com/img/i_n15402.webp?x28602',
        cardimg: 'https://genshin.honeyhunterworld.com/img/i_n15402_gacha_icon.webp?x28602',
        type: "Bow",
        desc: "",
        birthday: null,
        obtainableby: "Weapon Banner",
        title: null,
        altname: null,
        constellation: null,
        stars: "4",
        standard: true
    },
    {
        name: "The Widsith",
        wishimg: 'https://genshin.honeyhunterworld.com/img/i_n14402_gacha_icon.webp?x28602',
        profileimg: 'https://genshin.honeyhunterworld.com/img/i_n14402.webp?x28602',
        cardimg: 'https://genshin.honeyhunterworld.com/img/i_n14402_gacha_icon.webp?x28602',
        type: "Catalyst",
        desc: "",
        birthday: null,
        obtainableby: "Weapon Banner",
        title: null,
        altname: null,
        constellation: null,
        stars: "4",
        standard: true
    },
    {
        name: "Raven Bow",
        wishimg: 'https://genshin.honeyhunterworld.com/img/i_n15301_gacha_icon.webp?x28602',
        profileimg: 'https://genshin.honeyhunterworld.com/img/i_n15301.webp?x28602',
        cardimg: 'https://genshin.honeyhunterworld.com/img/i_n15301_gacha_icon.webp?x28602',
        type: "Bow",
        desc: "",
        birthday: null,
        obtainableby: "Weapon Banner",
        title: null,
        altname: null,
        constellation: null,
        stars: "3",
        standard: true
    },
    {
        name: "Sharpshooter's Oath",
        wishimg: 'https://genshin.honeyhunterworld.com/img/i_n15302_gacha_icon.webp?x28602',
        profileimg: 'https://genshin.honeyhunterworld.com/img/i_n15301.webp?x28602',
        cardimg: 'https://genshin.honeyhunterworld.com/img/i_n15302_gacha_icon.webp?x28602',
        type: "Bow",
        desc: "",
        birthday: null,
        obtainableby: "Weapon Banner",
        title: null,
        altname: null,
        constellation: null,
        stars: "3",
        standard: true
    },
    {
        name: "Slingshot",
        wishimg: 'https://genshin.honeyhunterworld.com/img/i_n15304_gacha_icon.webp?x28602',
        profileimg: 'https://genshin.honeyhunterworld.com/img/i_n15304.webp?x28602',
        cardimg: 'https://genshin.honeyhunterworld.com/img/i_n15304_gacha_icon.webp?x28602',
        type: "Bow",
        desc: "",
        birthday: null,
        obtainableby: "Weapon Banner",
        title: null,
        altname: null,
        constellation: null,
        stars: "3",
        standard: true
    },
    {
        name: "Emerald Orb",
        wishimg: 'https://genshin.honeyhunterworld.com/img/i_n14304_gacha_icon.webp?x28602',
        profileimg: 'https://genshin.honeyhunterworld.com/img/i_n14304.webp?x28602',
        cardimg: 'https://genshin.honeyhunterworld.com/img/i_n14304_gacha_icon.webp?x28602',
        type: "Catalyst",
        desc: "",
        birthday: null,
        obtainableby: "Weapon Banner",
        title: null,
        altname: null,
        constellation: null,
        stars: "3",
        standard: true
    },
    {
        name: "Magic Guide",
        wishimg: 'https://genshin.honeyhunterworld.com/img/i_n14301_gacha_icon.webp?x28602',
        profileimg: 'https://genshin.honeyhunterworld.com/img/i_n14301.webp?x28602',
        cardimg: 'https://genshin.honeyhunterworld.com/img/i_n14301_gacha_icon.webp?x28602',
        type: "Catalyst",
        desc: "",
        birthday: null,
        obtainableby: "Weapon Banner",
        title: null,
        altname: null,
        constellation: null,
        stars: "3",
        standard: true
    },
    {
        name: "Thrilling Tales of Dragon Slayers",
        wishimg: 'https://genshin.honeyhunterworld.com/img/i_n14302.webp?x28602',
        profileimg: 'https://genshin.honeyhunterworld.com/img/i_n14302.webp?x28602',
        cardimg: 'https://genshin.honeyhunterworld.com/img/i_n14302.webp?x28602',
        type: "Catalyst",
        desc: "",
        birthday: null,
        obtainableby: "Weapon Banner",
        title: null,
        altname: null,
        constellation: null,
        stars: "3",
        standard: true
    },
    {
        name: "Bloodtainted Greatsword",
        wishimg: 'https://genshin.honeyhunterworld.com/img/i_n12302_gacha_icon.webp?x28602',
        profileimg: 'https://genshin.honeyhunterworld.com/img/i_n12302.webp?x28602',
        cardimg: 'https://genshin.honeyhunterworld.com/img/i_n12302_gacha_icon.webp?x28602',
        type: "Claymore",
        desc: "",
        birthday: null,
        obtainableby: "Weapon Banner",
        title: null,
        altname: null,
        constellation: null,
        stars: "3",
        standard: true
    },
    {
        name: "Debate Club",
        wishimg: 'https://genshin.honeyhunterworld.com/img/i_n12305_gacha_icon.webp?x28602',
        profileimg: 'https://genshin.honeyhunterworld.com/img/i_n12305.webp?x28602',
        cardimg: 'https://genshin.honeyhunterworld.com/img/i_n12305_gacha_icon.webp?x28602',
        type: "Claymore",
        desc: "",
        birthday: null,
        obtainableby: "Weapon Banner",
        title: null,
        altname: null,
        constellation: null,
        stars: "3",
        standard: true
    },
    {
        name: "Ferrous Shadow",
        wishimg: 'https://genshin.honeyhunterworld.com/img/i_n12301_gacha_icon.webp?x28602',
        profileimg: 'https://genshin.honeyhunterworld.com/img/i_n12301.webp?x28602',
        cardimg: 'https://genshin.honeyhunterworld.com/img/i_n12301_gacha_icon.webp?x28602',
        type: "Claymore",
        desc: "",
        birthday: null,
        obtainableby: "Weapon Banner",
        title: null,
        altname: null,
        constellation: null,
        stars: "3",
        standard: true
    },
    {
        name: "Black Tassel",
        wishimg: 'https://genshin.honeyhunterworld.com/img/i_n13303_gacha_icon.webp?x28602',
        profileimg: 'https://genshin.honeyhunterworld.com/img/i_n13303.webp?x28602',
        cardimg: 'https://genshin.honeyhunterworld.com/img/i_n13303_gacha_icon.webp?x28602',
        type: "Polearm",
        desc: "",
        birthday: null,
        obtainableby: "Weapon Banner",
        title: null,
        altname: null,
        constellation: null,
        stars: "3",
        standard: true
    },
    {
        name: "Cool Steel",
        wishimg: 'https://genshin.honeyhunterworld.com/img/i_n11301_gacha_icon.webp?x28602',
        profileimg: 'https://genshin.honeyhunterworld.com/img/i_n11301.webp?x28602',
        cardimg: 'https://genshin.honeyhunterworld.com/img/i_n11301_gacha_icon.webp?x28602',
        type: "Sword",
        desc: "",
        birthday: null,
        obtainableby: "Weapon Banner",
        title: null,
        altname: null,
        constellation: null,
        stars: "3",
        standard: true
    },
    {
        name: "Harbinger of Dawn",
        wishimg: 'https://genshin.honeyhunterworld.com/img/i_n11302_gacha_icon.webp?x28602',
        profileimg: 'https://genshin.honeyhunterworld.com/img/i_n11302.webp?x28602',
        cardimg: 'https://genshin.honeyhunterworld.com/img/i_n11302_gacha_icon.webp?x28602',
        type: "Sword",
        desc: "",
        birthday: null,
        obtainableby: "Weapon Banner",
        title: null,
        altname: null,
        constellation: null,
        stars: "3",
        standard: true
    },
    {
        name: "Skyrider Sword",
        wishimg: 'https://genshin.honeyhunterworld.com/img/i_n11306_gacha_icon.webp?x28602',
        profileimg: 'https://genshin.honeyhunterworld.com/img/i_n11306.webp?x28602',
        cardimg: 'https://genshin.honeyhunterworld.com/img/i_n11306_gacha_icon.webp?x28602',
        type: "Sword",
        desc: "",
        birthday: null,
        obtainableby: "Weapon Banner",
        title: null,
        altname: null,
        constellation: null,
        stars: "3",
        standard: true
    },
];
</script>

<style scoped>
.indexcontainer{
  display: grid;
  grid-template-columns: repeat(6, 1fr);
  justify-content: space-around;
  align-items: center;
}
</style>